[package]
name = "rs_lib"
version = "0.0.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "z"
debug = true

[dependencies]
wasm-bindgen = "=0.2.81"
image = "0.24.5"
rustface = "0.1.7"
wee_alloc = "0.4.5"
